export const
    GET_STANDUP_GROUPS = 'GET_STANDUP_GROUPS',
    SET_STANDUP_GROUPS = 'SET_STANDUP_GROUPS',
    CREATE_STANDUP_GROUP = 'CREATE_STANDUP_GROUP',
    ADD_STANDUP_GROUP = 'ADD_STANDUP_GROUP',
    SELECT_STANDUP_GROUP = 'SELECT_STANDUP_GROUP'
