export const
    GET_STANDUP_REPORTS = 'GET_STANDUP_REPORTS',
    SET_STANDUP_REPORTS = 'SET_STANDUP_REPORTS',
    CREATE_STANDUP_REPORT = 'CREATE_STANDUP_REPORT',
    ADD_STANDUP_REPORT = 'ADD_STANDUP_REPORT',
    SET_STANDUP_REPORT_PERIODS = 'SET_STANDUP_REPORT_PERIODS'
