export const
    GET_STANDUP_ROWS = 'GET_STANDUP_ROWS',
    SET_STANDUP_ROWS = 'SET_STANDUP_ROWS',
    CREATE_STANDUP_ROW = 'CREATE_STANDUP_ROW',
    ADD_STANDUP_ROW = 'ADD_STANDUP_ROW',
    GET_STANDUP_ROW_METRICS = 'GET_STANDUP_ROW_METRICS',
    SET_STANDUP_ROW_METRICS = 'SET_STANDUP_ROW_METRICS'
